// Pricing
const FETCH_PRICING_DATA_SUCCESS = 'FETCH_PRICING_DATA_SUCCESS';
const FETCH_PRICING_DATA_FAIL = 'FETCH_PRICING_DATA_FAIL';

export { FETCH_PRICING_DATA_SUCCESS, FETCH_PRICING_DATA_FAIL };
